In [38]:
import numpy as np
from scipy import stats

In [6]:
def Get_OBJ_Data(path_to_data, file_name):
    # Dictionary storing OBJ data
    obj = {
    "v": [],
    "f": []
    }

    # Parses and reads OBJ
    # Assumes Specific Format
    with open(f"{path_to_data}{file_name}.obj") as f:
        for i, line in enumerate(f):
            tokenized_line = line.split()
            key = tokenized_line[0]
            
            if key in ["mtllib", "usemtl"]:
                # could be important in the future             
                continue
            elif key == "f":
                numbers_pairs = [x.split("/") for x in tokenized_line[1:]]
                obj[key].append(list(map(lambda x: int(x[0]), numbers_pairs)))
            else:
                numbers = [float(x) for x in tokenized_line[1:]]
                obj[key].append(numbers)

    for key,value in obj.items():
        obj[key] = np.array(value)

    return obj

In [114]:
obj = Get_OBJ_Data('objs/p3d/results/', 'mesh_1_cube')
f = np.round(obj['v'][obj['f'][0] - 1] * 49)
v1 = f[1] - f[0]
v2 = f[2] - f[0]

norm = np.cross(v1, v2)
print(f)

midpoint = (f[1] - f[2]) /2 + f[2] - norm / 2


print(midpoint)

[[ 0.  2. 36.]
 [ 0.  2. 37.]
 [ 0.  3. 36.]]
[ 0.5  2.5 36.5]


In [118]:
cube_world = np.load('objs/p3d/results/cube_world_mesh_1.npy')
faces = np.round(obj['v'][(obj['f'] - 1)[:]] * 49).astype('int32')
v1 = faces[:, 1] - faces[:, 0]
v2 = faces[:, 2] - faces[:, 0]

print(v1.shape)
print(v2.shape)

norm = np.cross(v1, v2)
print(norm.shape)
print(faces.shape)

midpoint = (faces[:, 1] - faces[:, 2]) /2 + faces[:, 2] - norm / 2
print(midpoint.shape)

(16896, 3)
(16896, 3)
(16896, 3)
(16896, 3, 3)
(16896, 3)


In [120]:
xyz = midpoint.astype('int32')
np.all(cube_world[xyz[:, 0], xyz[:, 1], xyz[:, 2]] == 1)

True

In [75]:

coords = stats.mode(faces, axis=1)[0].squeeze()

for x, y, z in coords:
    print(cube_world[x, y, z])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


IndexError: index 50 is out of bounds for axis 2 with size 50